const menuList=[
    {
      title:'系统管理',
      key:'/system',
      children:[
        {
          title:'权限管理',
          key:'/system/limit'
        },
        {
          title:'角色管理',
          key:'/system/role'
        }
      ]
    },
    {
      title:'组织管理',
      key:'/organization',
      children:[
          {
            title:'门店管理',
            key:'/organization/shop'
          },
          {
            title:'会员管理',
            key:'/organization/member'
          }
      ]
    },
    {
      title:'收益管理',
      key:'/income',
      children:[
          {
              title:'商城收益',
              key:'/income/market'
          }
      ]
    },
    {
      title:'人员管理',
      key:'/person',
      children:[
          {
              title:'职位管理',
              key:'/person/position'
          },
          {
              title:'员工管理',
              key:'/person/staff'
          }
      ]
    },
    {
        title:'产品管理',
        key:'/product',
        children:[
            {
                title:'商品类别管理',
                key:'/product/category'
            },
            {
                title:'商品管理',
                key:'/product/goods'
            },
            {
                title:'项目类别管理',
                key:'/product/classify'
            },
            {
                title:'项目管理',
                key:'/product/project'
            }
        ]
    },
    {
        title:'客户管理',
        key:'/customer',
        children:[
            {
                title:'会员管理',
                key:'/customer/shopMember'
            },
            {
                title:'充值记录',
                key:'/customer/invest'
            },
            {
                title:'预约管理',
                key:'/customer/booking'
            },
            {
                title:'商城订单管理',
                key:'/customer/order'
            }
        ]
    },
    {
      title:'其他',
      key:'/others'
    }
  ]
  export default menuList